const apartmentListings = [
    {
        id: 1,
        name: "Ori On The Ave",
        address: "5263 University Way NE, Seattle, WA 98105",
        units: "Studio apartments",
        price: "$1,538–$1,934 per month",
        rating: 4.5,
        genres: ["Studio", "Budget-Friendly"],
        amenities: [
            "BBQ & Fire Pit",
            "24-hrs Surveillance Security",
            "Rooftop Deck", 
            "Balcony Patio",  
            "Club Room",
            "Conference Room",
            "Pet-friendly",
            "Bike Room",                      
            "Full Kitchenettes",
            "In-unit WD",                                                      
            ],
        location:"Ori on the Ave is an apartment community located in King County and the 98105 ZIP Code. This area is served by the Seattle Public Schools attendance zone."
    },
    {
        id: 2,
        name: "Arista Catering",
        address: "4715 25th Ave NE, Seattle, WA 98105",
        units: "Studio to 3-bedroom apartments",
        price: "$2,035–$14,805 per month",
        rating: 4.0,
        genres: ["Luxury", "Family-Friendly"],
        amenities: [
            "Concierge",
            "Roof Terrace",
            "Grill",
            "Package Service",
            "Maintenance on site",
            "Property Manager on Site",
            "Concierge",
            "Guest Apartment",
            "Pet Play Area",
            "Pet Washing Station",
            "Lounge",
            "Multi Use Room",
            "Sauna",
            "Spa",
            "Bicycle Storage",
            "Roof Terrace",
            "Courtyard",
            "Grill",
            "In-Unit Washer/Dryer",
            "Walk-In Closets",
            "Island Kitchen",
            "Double Vanities",
            "Dishwasher",
            "Balcony"
        ]
        
    },
    {
        id: 3,
        name: "The M Seattle",
        address: "4700 Brooklyn Ave NE, Seattle, WA 98105",
        units: "Studio to 4-bedroom apartments",
        price: "$1,350–$2,695 per month",
        rating: 3.5,
        genres: ["Studio", "Affordable"],
        amenities: [
            "Rooftop Lounge: Featuring panoramic views of the Seattle skyline and Mount Rainier, complete with seating areas and BBQ grills.",
            "Fitness Center: A state-of-the-art gym equipped with cardio machines, weights, and open space.",
            "Pet-Friendly Spaces: The M is pet-friendly, with designated pet areas.",
            "Community Areas: Stylishly designed lounges, study rooms, and co-working spaces.",
            "Secure Access: Keycard entry and on-site security ensure residents' safety.",
            "Package Lockers: Convenient package management for deliveries.",
        ],
        location: "Nestled in a prime spot in the U-District, a short walk or bike ride from the University of Washington.",
    },
];

export default apartmentListings;
